### ISSUE TITLE
Weights and biases for SC-MBM

### ISSUE THREAD

**Issue by AlexanderNutalapati** [zjc062/mind-vis#10]
Greetings,

First of all I am really fascinated by the work Your team has done. Thank you!
I am excited to run and test your code, but unfortunately I do not have the resources to train the SC-MBM part in a reasonable amount of time.
Is it possible for You to share the weights and biases that You've acquired during Your training? I would appreciate it a lot.

Regards, Alexander.

**Comment by zjc062** [comment]
Hi Alexander,

Thank you for your interest in our work! 

The pre-trained models for SC-MBM can be found in the 'pretrains' folder on Figshare. The checkpoint for each dataset is labeled as "fmri_encoder.pth" and corresponds to SC-MBM trained on the HCP dataset along with the target dataset.

If you have any further questions or need additional assistance, please don't hesitate to reach out. :)
