### ISSUE TITLE
Training correlations when applied MBM model to another dataset

### ISSUE THREAD

**Issue by sfxjh** [zjc062/mind-vis#11]
HI! I really appreciate your work and plan to follow it in our area. By the way, may I ask a question about the training correlations calculated by torch.corrcoef?

I have applied the MBM model to another dataset and made several changes. However, I have recently found that the model may not perform well under the correlation metric. Could you please tell me the training correlations in your settings, and what is your opinion on this phenomenon?
![image](https://user-images.githubusercontent.com/22070963/224463446-f657b438-6f7f-4557-9fe3-df8332f14737.png)

The attached image shows the models that we have trained recently, with the red and grey lines representing the models.

**Comment by zjc062** [comment]
Hi there,

Thanks for your interest in our work! I actually feel like this correlation looks pretty good already (if you are referring to the correlation between reconstructed fMRI and original fMRI). Also, the correlation may or may not reflect the performance of your downstream task. 

You may try on the image reconstruction task and see how it goes! :)

Good luck!

**Comment by sfxjh** [comment]
Thank you for your response! I appreciate your feedback on the correlation between the reconstructed fMRI and the original fMRI. I am glad to hear that you think the correlation looks good.

I understand that the correlation may not necessarily reflect the performance of my downstream task, but I will certainly take your suggestion and try it out on the our tasks. I will keep you updated on my progress.
