### ISSUE TITLE
Encountered problem while running Stage B

### ISSUE THREAD

**Issue by zengbohan0217** [zjc062/mind-vis#13]
Thank you for your contribution to the project. We encountered the following issue while running the code: in code/eval_metrics.py, line 119, in n_way_top_k_acc, acc = accuracy(pred_picked.unsqueeze(0), torch.tensor([0], device=pred.device), top_k=top_k) TypeError: accuracy() missing 1 required positional argument: 'task'. Could you please advise on how to fix this?

**Comment by jqin4749** [comment]
It seems that torchmetrics updated their API. For torchmetrics > 0.9.2, try 
`acc = accuracy(pred_picked.unsqueeze(0), torch.tensor([0], device=pred.device), 
                    top_k=top_k, task = 'multiclass')`
